### ISSUE TITLE
Front-end Development ToDo

### ISSUE THREAD

**Issue by josefpolasek** [skkuoss/AskYoda_dashboard#1]
## Main ToDo
- [x] basic HTML layout  @josefpolasek
- [x] basic CSS style @josefpolasek
- [ ] input for link to Spotify song @BestevenSKKU 
- [ ] Ask Yoda button -> algorithm @BestevenSKKU 
- [ ] window with recommended list @borquezz 
---
## Additional
- [ ] make a website responsive for phones
- [ ] input fields (with recommendation)
- [ ] special features (random song selection)
- [ ] add some cool animations/effects ...
